INSERT INTO main_muscle_group (main_muscle_group_id, name, description) VALUES
  ('1', 'Arms', 'The arms include the biceps, triceps, and brachialis muscles, which are responsible for arm flexion and extension.'),
  ('2', 'Abdominals', 'The abdominal muscles, including the rectus abdominis, obliques, and transverse abdominis, are responsible for trunk flexion and rotation.'),
  ('3', 'Forearms', 'The forearm muscles, including the wrist flexors and extensors, are responsible for wrist and hand movement.'),
  ('4', 'Shoulders', 'The shoulder muscles, including the deltoids and the rotator cuff, are responsible for shoulder abduction, flexion, and rotation.'),
  ('5', 'Chest', 'The chest muscles, including the pectoralis major and minor, are responsible for shoulder adduction and flexion. '),
  ('6', 'Back', 'The back muscles, including the latissimus dorsi, rhomboids, erector spinae, and trapezius, are responsible for back extension, rotation, and scapular movement.'),
  ('7', 'Legs', 'The leg muscles, including the quadriceps, hamstrings, glutes, and calves, are responsible for lower body movement, including walking, running, jumping, and squatting.')
;

INSERT INTO muscle_group (muscle_group_id, main_muscle_group_id, name, description) VALUES
  ('1', '1', 'Biceps', 'The biceps (short for biceps brachii) are a muscle group located on the front of the upper arm. They consist of two heads (hence the name "bi" meaning two) and are responsible for flexing the elbow joint and rotating the forearm. The long head of the biceps originates from the scapula bone and the short head from the coracoid process of the scapula, both joining to form the biceps muscle belly which attaches to the radius bone of the forearm via the biceps tendon.'),
  ('2', '1', 'Triceps', 'The triceps (short for triceps brachii) are a muscle group located on the back of the upper arm. They consist of three heads and are responsible for extending the elbow joint. The long head of the triceps originates from the scapula bone, the lateral head from the humerus bone, and the medial head from the humerus bone below the lateral head. All three heads join together to form the triceps muscle belly which attaches to the ulna bone of the forearm via the triceps tendon.'),
  ('3', '2', 'Rectus Abdominis', 'The rectus abdominis (often referred to as the "abs") is a paired muscle that runs vertically along the anterior (front) wall of the abdomen. It is commonly referred to as the "six-pack" muscle due to its visible appearance in individuals with low body fat. The rectus abdominis plays an important role in stabilizing the trunk and flexing the spine. It is involved in many everyday movements, such as bending forward, sitting up, and twisting the torso'),
  ('4', '2', 'Transverse Abdominis', 'The transverse abdominis (TVA) is a deep muscle located beneath the rectus abdominis and obliques, and is the innermost muscle of the abdominal wall. It runs horizontally across the abdomen, and unlike other abdominal muscles, it is not involved in spine flexion or rotation. The TVA plays a vital role in stabilizing the spine and pelvis, and it acts as a natural corset for the body. It works in conjunction with other core muscles to provide support to the lower back and pelvis, especially during movements such as lifting, twisting, and bending. The TVA also helps to maintain intra-abdominal pressure and improves breathing efficiency.'),
  ('5', '2', 'Obliques', 'The obliques (short for external and internal obliques) are a group of muscles located on the sides of the abdomen, running diagonally from the lower ribs to the pelvis. They play an important role in trunk rotation, lateral flexion, and stabilization of the spine. The external obliques are the outermost layer of the oblique muscles and are responsible for rotating the trunk and flexing the spine to the side. The internal obliques are located beneath the external obliques and work together to rotate the trunk in the opposite direction.'),
  ('6', '3', 'Wrist Flexors', 'The wrist flexors are a group of muscles located on the anterior (front) aspect of the forearm, which are responsible for flexing the wrist joint and bringing the palm of the hand towards the forearm.'),
  ('7', '3', 'Wrist Extensors', 'The wrist extensors are a group of muscles located on the posterior (back) aspect of the forearm, which are responsible for extending the wrist joint and bringing the back of the hand towards the forearm.'),
  ('8', '4', 'Anterior Deltoid', 'The anterior deltoid is one of the three heads of the deltoid muscle located at the front of the shoulder. It originates from the clavicle and inserts into the humerus bone of the upper arm. The anterior deltoid plays a crucial role in the movement of the shoulder joint. The main function of the anterior deltoid is to flex the arm at the shoulder joint and bring the arm forward. It also assists in abduction (lifting the arm out to the side) and horizontal flexion (bringing the arm across the body). '),
  ('9', '4', 'Middle Deltoid', 'The middle deltoid is one of the three heads of the deltoid muscle located in the middle of the shoulder. It originates from the scapula bone and inserts into the humerus bone of the upper arm. The middle deltoid plays a crucial role in the movement of the shoulder joint. The main function of the middle deltoid is to abduct the arm (lift it away from the body) and bring the arm to a horizontal position. It also assists in shoulder extension (bringing the arm backwards). '),
  ('10', '4', 'Posterior Deltoid', 'The posterior deltoid is the third head of the deltoid muscle located at the back of the shoulder. It originates from the scapula bone and inserts into the humerus bone of the upper arm. The posterior deltoid plays a crucial role in the movement of the shoulder joint. The main function of the posterior deltoid is to horizontally extend the arm and rotate it inwardly. It also assists in shoulder extension (bringing the arm backwards). '),
  ('11', '4', 'Teres Major', 'The teres major is a muscle located in the upper back region, running from the bottom edge of the shoulder blade to the upper arm bone. It is positioned below the larger and more well-known latissimus dorsi muscle. Despite its relatively small size, the teres major plays an important role in the movement and stability of the shoulder joint.'),
  ('12', '5', 'Pectoralis Major', 'The pectoralis major is a large, fan-shaped muscle located on the chest. It is divided into two parts: the clavicular head and the sternal head, which originate from the collarbone and sternum respectively, and they both converge into a single tendon that inserts into the humerus bone of the upper arm. The main function of the pectoralis major is to horizontally adduct the arm (bring it across the body), as well as medially rotate the arm and pull it forward. '),
  ('13', '6', 'Latissimus Dorsi', 'The latissimus dorsi is a large, flat muscle located in the middle and lower back. It originates from the lower spine and iliac crest (hip bone) and inserts into the upper arm bone (humerus). It is commonly referred to as the "lats." The main function of the latissimus dorsi is to perform shoulder extension, adduction, and internal rotation.'),
  ('14', '6', 'Rhomboids', 'The rhomboids are a pair of muscles located in the upper back between the spine and the shoulder blades. There are two types of rhomboids: the rhomboid major and the rhomboid minor. The rhomboids function to retract, elevate, and stabilize the shoulder blades. This means that they pull the shoulder blades together towards the spine and upwards towards the ears. The rhomboids also help to maintain proper alignment and positioning of the shoulder blades '),
  ('15', '6', 'Erector Spinae', 'The erector spinae is a group of muscles that runs along the length of the spine, from the base of the skull to the pelvis. It is composed of three muscle groups: the iliocostalis, longissimus, and spinalis.'),
  ('16', '6', 'Trapezius', 'The trapezius muscle is a large, triangular muscle located in the upper back and neck. It extends from the base of the skull to the middle of the back and out towards the shoulder blades. The trapezius muscle has several functions, including shoulder elevation, depression, retraction, and rotation. It is also involved in movements of the head and neck, such as rotation and extension. '),
  ('17', '7', 'Quadriceps', 'The quadriceps, also known as the quads, are a group of four muscles located in the front of the thigh. The quadriceps include the rectus femoris, vastus lateralis, vastus medialis, and vastus intermedius. The quadriceps are responsible for extending the knee joint and straightening the leg.'),
  ('18', '7', 'Hamstrings', 'The hamstrings are a group of three muscles located in the back of the thigh. They include the biceps femoris, semitendinosus, and semimembranosus muscles. The hamstrings are responsible for flexing the knee joint, bending the leg at the knee, and extending the hip joint'),
  ('19', '7', 'Glutes', 'The glutes, also known as the gluteal muscles, are a group of three muscles located in the buttocks: the gluteus maximus, gluteus medius, and gluteus minimus. The glutes are responsible for hip extension, abduction, and rotation.'),
  ('20', '7', 'Calves', 'The calves, also known as the gastrocnemius and soleus muscles, are located in the lower leg and are responsible for plantar flexion of the foot (pointing the toes downward) and aiding in ankle stabilization. The gastrocnemius muscle is the larger of the two and is primarily responsible for the appearance of the calf muscle, while the soleus muscle is located underneath and is more involved in stabilization and endurance.')
;

